## **Staff Turnover HR - ETL**

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
staff_df = pd.read_csv('Data/staff_turnover_HR.csv')
staff_df.head()

,EmpID,Age,Attrition,BusinessTravel,DailyRate,Department,Manage ID,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM650,53,No,Travel_Rarely,102,Research & Development,M007,23,4,Life Sciences,1,901,4,Female,72,3,4,Research Director,4,Single,14275,20206,6,Y,No,18,3,3,80,0,33,0,3,12,9,3,8.0
1,RM015,28,Yes,Travel_Rarely,103,Research & Development,M507,24,3,Life Sciences,1,19,3,Male,50,2,1,Laboratory Technician,3,Single,2028,12947,5,Y,Yes,14,3,2,80,0,6,4,3,4,2,0,3.0
2,RM1111,35,Yes,Travel_Rarely,104,Research & Development,M507,2,3,Life Sciences,1,1569,1,Female,69,3,1,Laboratory Technician,1,Divorced,2074,26619,1,Y,Yes,12,3,4,80,1,1,2,3,1,0,0,0.0
3,RM1438,39,No,Non-Travel,105,Research & Development,M331,9,3,Life Sciences,1,2022,4,Male,87,3,5,Manager,4,Single,19431,15302,2,Y,No,13,3,3,80,0,21,3,2,6,0,1,3.0
4,RM311,31,No,Travel_Rarely,106,Human Resources,M106,2,3,Human Resources,1,424,1,Male,62,2,2,Human Resources,1,Married,6410,17822,3,Y,No,12,3,4,80,0,9,1,3,2,2,1,0.0

In [3]:
# Informacion general del dataframe
staff_df.describe(include='object')
staff_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   Attrition                 1480 non-null   object
 3   BusinessTravel            1480 non-null   object
 4   DailyRate                 1480 non-null   int64
 5   Department                1480 non-null   object
 6   Manage ID                 1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  MonthlyRate               1480 non-null   int64
 22  NumCompaniesWorked        1480 non-null   int64
 23  Over18                    1480 non-null   object
 24  OverTime                  1480 non-null   object
 25  PercentSalaryHike         1480 non-null   int64
 26  PerformanceRating         1480 non-null   int64
 27  RelationshipSatisfaction  1480 non-null   int64
 28  StandardHours             1480 non-null   int64
 29  StockOptionLevel          1480 non-null   int64
 30  TotalWorkingYears         1480 non-null   int64
 31  TrainingTimesLastYear     1480 non-null   int64
 32  WorkLifeBalance           1480 non-null   int64
 33  YearsAtCompany            1480 non-null   int64
 34  YearsInCurrentRole        1480 non-null   int64
 35  YearsSinceLastPromotion   1480 non-null   int64
 36  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(11)
memory usage: 427.9+ KB

In [4]:
# Numero de nulos por columna
staff_df.isnull().sum()

EmpID                        0
Age                          0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
Manage ID                    0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [5]:
# Selección de columnas relevantes para el análisis
columns_to_keep = ['EmpID','Age','Attrition','BusinessTravel','Department','DistanceFromHome','EducationField','EnvironmentSatisfaction','Gender','JobRole','JobSatisfaction','MaritalStatus','MonthlyIncome','MonthlyRate','NumCompaniesWorked','OverTime','PercentSalaryHike','PerformanceRating','RelationshipSatisfaction','TotalWorkingYears','TrainingTimesLastYear','WorkLifeBalance','YearsAtCompany','YearsInCurrentRole','YearsSinceLastPromotion','YearsWithCurrManager']
staff_df = staff_df[columns_to_keep]
staff_df.shape

(1480, 26)

In [6]:
# Eliminación de duplicados
staff_df.drop_duplicates(inplace=True)
staff_df.shape

(1473, 26)

In [7]:
# Estadisticas descriptivas de las columnas numéricas 
staff_df.describe()

,Age,DistanceFromHome,EnvironmentSatisfaction,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1416.000000
mean,36.917176,9.196877,2.723693,2.728445,6500.228785,14321.376103,2.693143,15.212492,3.153428,2.712152,11.277665,2.800407,2.761711,7.004752,4.228106,2.183978,4.117232
std,9.130690,8.107754,1.093006,1.103163,4706.053923,7115.540450,2.496914,3.657230,0.360522,1.081575,7.776228,1.289411,0.705838,6.121004,3.621096,3.220301,3.559344
min,18.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,2.000000,2.000000,2.000000,2911.000000,8053.000000,1.000000,12.000000,3.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,7.000000,3.000000,3.000000,4908.000000,14242.000000,2.000000,14.000000,3.000000,3.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,14.000000,4.000000,4.000000,8380.000000,20467.000000,4.000000,18.000000,3.000000,4.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,29.000000,4.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [8]:
# Estadisticas descriptivas de las columnas categóricas
staff_df.describe(include=['object','string'])

,EmpID,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
count,1473,1473,1473,1473,1473,1473,1473,1473,1473
unique,1470,2,4,3,6,2,9,3,2
top,RM1465,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,No
freq,2,1236,1038,963,606,884,326,728,1057

In [9]:
# Hacemos un conteo de los valores únicos por columna categórica para detectar posibles errores de tipeo o inconsistencias en los datos

# Listamos las columnas que son de tipo object o string
staff_df_Columns_Object = staff_df.select_dtypes(include=['object','string']).columns.tolist()
staff_df_Columns_Object.remove('EmpID')  # Eliminamos la columna 'EmpID' de la lista ya que es un identificador único y no es relevante para este análisis

# Creamos un diccionario extrayendo los valores únicos de cada una
datos_unicos = {col: pd.Series(staff_df[col].unique()) for col in staff_df_Columns_Object}

# Creamos el DataFrame final
df_unicos = pd.DataFrame(datos_unicos)
df_unicos

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
0,No,Travel_Rarely,Research & Development,Life Sciences,Female,Research Director,Single,No
1,Yes,Non-Travel,Human Resources,Human Resources,Male,Laboratory Technician,Divorced,Yes
2,NaN,Travel_Frequently,Sales,Technical Degree,NaN,Manager,Married,NaN
3,NaN,TravelRarely,NaN,Medical,NaN,Human Resources,NaN,NaN
4,NaN,NaN,NaN,Other,NaN,Sales Executive,NaN,NaN
5,NaN,NaN,NaN,Marketing,NaN,Research Scientist,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,Healthcare Representative,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,Manufacturing Director,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,Sales Representative,NaN,NaN

#### ⚠️ **ERRORES DE TIPEO** ⚠️
1. Notamos que en la columna 'BusinessTravel' hay un erros de tipeo ya que 'Travel_Rarely' y 'TravelRarely' son la misma clasificación pero se detectan como diferentes debido al guión bajo.

2. Cambiaremos la clasificación "Non-Travel" por "Non_Travel" para ir acorde al resto.

In [10]:
staff_df.loc[staff_df['BusinessTravel'] == 'TravelRarely', 'BusinessTravel'] = 'Travel_Rarely'
staff_df.loc[staff_df['BusinessTravel'] == 'Non-Travel', 'BusinessTravel'] = 'Non_Travel'

In [11]:
print(staff_df['BusinessTravel'].unique())

['Travel_Rarely' 'Non_Travel' 'Travel_Frequently']

#### ⚠️ **Duplicados en 'EmpID'** ⚠️

Notamos que estos duplicados son generados por la columna 'YearsWithCurrManager', ya que tiene dos valores distintos para un solo EmpID de 3 EmpID. 
Debido a que esta columna tiene valores nulos y reflexionando un poco más al respecto esta no es clave para nuestro análisis por lo que la eliminaremos.

In [12]:
# Verificar si hay duplicados en la columna 'EmpID'
staff_df[staff_df['EmpID'].duplicated(keep=False)]

,EmpID,Age,Attrition,BusinessTravel,Department,DistanceFromHome,EducationField,EnvironmentSatisfaction,Gender,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
546,RM1467,39,No,Travel_Rarely,Research & Development,6,Medical,4,Male,Healthcare Representative,1,Married,9991,21457,4,No,15,3,1,9,5,3,7,7,1,7.0
547,RM1467,39,No,Travel_Rarely,Research & Development,6,Medical,4,Male,Healthcare Representative,1,Married,9991,21457,4,No,15,3,1,9,5,3,7,7,1,1.0
827,RM1466,36,No,Travel_Frequently,Research & Development,23,Medical,3,Male,Laboratory Technician,4,Married,2571,12290,4,No,17,3,3,17,3,3,5,2,0,3.0
828,RM1466,36,No,Travel_Frequently,Research & Development,23,Medical,3,Male,Laboratory Technician,4,Married,2571,12290,4,No,17,3,3,17,3,3,5,2,0,2.0
1117,RM1465,26,No,Travel_Rarely,Sales,5,Other,4,Female,Sales Representative,3,Single,2966,21378,0,No,18,3,4,5,2,3,4,2,0,0.0
1118,RM1465,26,No,Travel_Rarely,Sales,5,Other,4,Female,Sales Representative,3,Single,2966,21378,0,No,18,3,4,5,2,3,4,2,0,5.0

In [13]:
# Eliminamos la columna 'YearsWithCurrManager' ya que no es relevante para el análisis y puede generar multicolinealidad con otras variables
staff_df = staff_df.drop(columns=['YearsWithCurrManager'])
staff_df.columns # Comprobamos que la columna ha sido eliminada correctamente

Index(['EmpID', 'Age', 'Attrition', 'BusinessTravel', 'Department',
       'DistanceFromHome', 'EducationField', 'EnvironmentSatisfaction',
       'Gender', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion'],
      dtype='object')

#### 💡 **Agregación de columnas categoricas**

A continuación haremos la agregación de nuevas columnas para hacer una clasificación en rangos de las columnas 'Age', 'MonthlyIncome', 'YearsAtCompany', 'TotalWorkingYears'. Esto lo haremos en esta parte ya que de esta manera ahorramos calcular estas con DAX de Power BI, con esto buscamos una optimización en el peso del informe generado.

In [ ]:

limites = [17, 25, 35, 45, 55, 120]

etiquetas = ["18-25", "26-35", "36-45", "46-55", "55+"]

staff_df["AgeGroup"] = pd.cut(
    staff_df["Age"], bins=limites, labels=etiquetas, right=True
)

   Age AgeGroup
0   53    46-55
1   28    26-35
2   35    26-35
3   39    36-45
4   31    26-35

In [15]:
staff_df['AgeGroup'].value_counts()  # Contamos el número de empleados en cada grupo de edad

AgeGroup
26-35    607
36-45    470
46-55    226
18-25    123
55+       47
Name: count, dtype: int64

In [16]:
limites = [1000, 5000, 10000, 15000, 20000]

etiquetas = ["Upto 5k", "5k-10k", "10k-15k", "15k+"]

staff_df["SalarySlab"] = pd.cut(
    staff_df["MonthlyIncome"], bins=limites, labels=etiquetas, right=True
)

In [17]:
staff_df['SalarySlab'].value_counts()  # Contamos el número de empleados en cada rango salarial

SalarySlab
Upto 5k    751
5k-10k     441
10k-15k    148
15k+       133
Name: count, dtype: int64

In [18]:
staff_df.to_csv('Data/staff_turnover_HR_cleaned.csv', index=False)  # Guardamos el DataFrame limpio en un nuevo archivo CSV